In [10]:
import pandas as pd
#data_df = pd.read_csv('clean_newsgroups.csv')
data_df = pd.read_csv('../Output/PubMedCleanArticle(normalize+lemmetize).csv', encoding='utf-8')

In [11]:
data_df.head(10)

Unnamed: 0                                            Article  \
0           0  Cancer and cure: A critical analysis. Cancer i...   
1           1  Tumor microenvironment: recent advances in var...   
2           2  Global Cancer Incidence and Mortality Rates an...   
3           3  Recent Updates on the Relationship between Can...   
4           4  What Is Cancer? This essay focuses on themes i...   
5           5  New methods in the diagnosis of cancer and gen...   
6           6  Cancer-associated fibroblasts in tumor microen...   
7           7  Clinical, Prognostic and Therapeutic Significa...   
8           8  Cancer prevention: from 1727 to milestones of ...   
9           9                                                NaN   

                                          lemmatized  Target Label Target Name  
0  ['cancer', 'cure', 'critical', 'analysis', 'ca...             1      Cancer  
1  ['tumor', 'microenvironment', 'recent', 'advan...             1      Cancer  
2  ['global', 'cancer', 'incidence', 'mortality',...             1      Cancer  
3  ['recent', 'update', 'relationship', 'cancer',...             1      Cancer  
4  ['cancer', 'essay', 'focus', 'theme', 'explain...             1      Cancer  
5  ['new', 'method', 'diagnosis', 'cancer', 'gene...             1      Cancer  
6  ['cancerassociated', 'fibroblast', 'tumor', 'm...             1      Cancer  
7  ['clinical', 'prognostic', 'therapeutic', 'sig...             1      Cancer  
8  ['cancer', 'prevention', 'milestone', 'past', ...             1      Cancer  
9                                            ['nan']             1      Cancer

In [12]:
import numpy as np
np.array(data_df['Target Label'])

array([1, 1, 1, ..., 5, 5, 5], dtype=int64)

In [13]:
np.array(data_df['Target Name'])

array(['Cancer', 'Cancer', 'Cancer', ..., 'Virus', 'Virus', 'Virus'],
      dtype=object)

In [14]:
import numpy as np
from sklearn.model_selection import train_test_split

train_corpus, test_corpus, train_label_nums, test_label_nums, train_label_names, test_label_names =\
                                 train_test_split(np.array(data_df['lemmatized']), np.array(data_df['Target Label']),
                                                       np.array(data_df['Target Name']), test_size=0.33, random_state=42)

train_corpus.shape, test_corpus.shape

((33500,), (16500,))

In [15]:
train_label_nums, test_label_nums

(array([3, 1, 1, ..., 4, 1, 2], dtype=int64),
 array([4, 1, 1, ..., 4, 5, 3], dtype=int64))

In [16]:
train_label_names, test_label_names

(array(['Genome', 'Cancer', 'Cancer', ..., 'Vaccine', 'Cancer', 'COVID-19'],
       dtype=object),
 array(['Vaccine', 'Cancer', 'Cancer', ..., 'Vaccine', 'Virus', 'Genome'],
       dtype=object))

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
# get bag of words features in sparse format
cv = CountVectorizer(min_df=0., max_df=1.)
cv_matrix = cv.fit_transform(data_df['lemmatized'])
cv_matrix

<50000x50719 sparse matrix of type '<class 'numpy.int64'>'
	with 1068237 stored elements in Compressed Sparse Row format>

In [18]:
from collections import Counter

trd = dict(Counter(train_label_names))
tsd = dict(Counter(test_label_names))

(pd.DataFrame([[key, trd[key], tsd[key]] for key in trd], 
             columns=['Target Label', 'Train Count', 'Test Count'])
.sort_values(by=['Train Count', 'Test Count'],
             ascending=False))

Target Label  Train Count  Test Count
0       Genome         6755        3245
4        Virus         6715        3285
3     COVID-19         6709        3291
2      Vaccine         6695        3305
1       Cancer         6626        3374

In [19]:
import nltk
(pd.Series(nltk.ngrams(data_df['lemmatized'], 2)).value_counts())[:3]

(['nan'], ['nan'])                                                                                                                                                                                 3303
(['nan'], ['uptake', 'study', 'crosssectional', 'survey', 'examining', 'insight', 'belief', 'objective', 'key', 'challenge', 'towards', 'successful', 'covid', 'vaccine', 'uptake', 'vaccine'])       2
(['nan'], ['attitude', 'towards', 'influenza', 'vaccine', 'potential', 'covid', 'vaccine', 'italy', 'objective', 'aimed', 'describing', 'attitude', 'towards', 'influenza', 'vaccination'])           2
dtype: int64

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import cross_val_score

# build BOW features on train articles
cv = CountVectorizer(binary=False, min_df=0.00002, max_df=0.6)
cv_train_features = cv.fit_transform(train_corpus)

In [21]:
print(cv_train_features.shape)

(33500, 40755)


In [22]:
print(cv_train_features)

  (0, 28141)	1
  (0, 2334)	1
  (0, 7059)	1
  (0, 29655)	1
  (0, 11385)	1
  (0, 1678)	1
  (0, 20791)	1
  (0, 7729)	1
  (0, 3223)	1
  (0, 4158)	1
  (0, 10671)	1
  (0, 14509)	1
  (0, 10243)	1
  (0, 33492)	1
  (0, 20715)	1
  (0, 3388)	1
  (0, 26743)	1
  (1, 3223)	1
  (1, 10243)	3
  (1, 27300)	4
  (1, 29676)	2
  (1, 34517)	5
  (1, 23717)	7
  (1, 24600)	3
  (1, 21247)	4
  :	:
  (33498, 35383)	1
  (33498, 8698)	1
  (33498, 11500)	1
  (33498, 12725)	1
  (33498, 197)	1
  (33498, 7457)	1
  (33498, 10162)	1
  (33498, 32975)	1
  (33498, 27107)	1
  (33498, 9246)	1
  (33498, 18694)	1
  (33498, 9231)	1
  (33498, 37592)	1
  (33498, 16521)	1
  (33498, 37376)	1
  (33498, 25349)	1
  (33498, 20114)	1
  (33498, 31465)	1
  (33498, 37179)	1
  (33498, 7859)	2
  (33498, 20115)	1
  (33498, 32654)	1
  (33498, 771)	1
  (33498, 1081)	1
  (33499, 23925)	1


In [23]:
# transform test articles into features
cv_test_features = cv.transform(test_corpus.astype('U'))
print(cv_test_features.shape)
print(cv_train_features)

(16500, 40755)
  (0, 28141)	1
  (0, 2334)	1
  (0, 7059)	1
  (0, 29655)	1
  (0, 11385)	1
  (0, 1678)	1
  (0, 20791)	1
  (0, 7729)	1
  (0, 3223)	1
  (0, 4158)	1
  (0, 10671)	1
  (0, 14509)	1
  (0, 10243)	1
  (0, 33492)	1
  (0, 20715)	1
  (0, 3388)	1
  (0, 26743)	1
  (1, 3223)	1
  (1, 10243)	3
  (1, 27300)	4
  (1, 29676)	2
  (1, 34517)	5
  (1, 23717)	7
  (1, 24600)	3
  (1, 21247)	4
  :	:
  (33498, 35383)	1
  (33498, 8698)	1
  (33498, 11500)	1
  (33498, 12725)	1
  (33498, 197)	1
  (33498, 7457)	1
  (33498, 10162)	1
  (33498, 32975)	1
  (33498, 27107)	1
  (33498, 9246)	1
  (33498, 18694)	1
  (33498, 9231)	1
  (33498, 37592)	1
  (33498, 16521)	1
  (33498, 37376)	1
  (33498, 25349)	1
  (33498, 20114)	1
  (33498, 31465)	1
  (33498, 37179)	1
  (33498, 7859)	2
  (33498, 20115)	1
  (33498, 32654)	1
  (33498, 771)	1
  (33498, 1081)	1
  (33499, 23925)	1


In [24]:
print('BOW model:> Train features shape:', cv_train_features.shape, ' Test features shape:', cv_test_features.shape)

BOW model:> Train features shape: (33500, 40755)  Test features shape: (16500, 40755)


In [25]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(penalty='l2', max_iter=1000, C=0.1, random_state=42)
lr.fit(cv_train_features, train_label_names)
lr_bow_cv_scores = cross_val_score(lr, cv_train_features, train_label_names, cv=5)
lr_bow_cv_mean_score = np.mean(lr_bow_cv_scores)
print('CV Accuracy (5-fold):', lr_bow_cv_scores)
print('Mean CV Accuracy:', lr_bow_cv_mean_score)
lr_bow_test_score = lr.score(cv_test_features, test_label_names)
print('Test Accuracy:', lr_bow_test_score)

CV Accuracy (5-fold): [0.81283582 0.80671642 0.8019403  0.80656716 0.81776119]
Mean CV Accuracy: 0.8091641791044776
Test Accuracy: 0.8161212121212121


In [26]:
from sklearn.svm import LinearSVC

svm = LinearSVC(penalty='l2', max_iter=100, C=0.001, random_state=42)
svm.fit(cv_train_features, train_label_names)
svm_bow_cv_scores = cross_val_score(svm, cv_train_features, train_label_names, cv=5)
svm_bow_cv_mean_score = np.mean(svm_bow_cv_scores)
print('CV Accuracy (5-fold):', svm_bow_cv_scores)
print('Mean CV Accuracy:', svm_bow_cv_mean_score)
svm_bow_test_score = svm.score(cv_test_features, test_label_names)
print('Test Accuracy:', svm_bow_test_score)

CV Accuracy (5-fold): [0.7958209  0.79850746 0.79134328 0.7958209  0.80522388]
Mean CV Accuracy: 0.7973432835820896
Test Accuracy: 0.8034545454545454


In [33]:
pd.DataFrame([['Logistic Regression', lr_bow_cv_mean_score, lr_bow_test_score],
              ['Linear SVM', svm_bow_cv_mean_score, svm_bow_test_score]],
              columns=['Model',  'CV Score (TF)', 'Test Score (TF)'],
             )

Model  CV Score (TF)  Test Score (TF)
0  Logistic Regression       0.809164         0.816121
1           Linear SVM       0.797343         0.803455